### ISSUE TITLE
LICENSE information

### ISSUE THREAD

**Issue by seyoung-hyun** [AloPeyk/AloPeykSnackbar#18]
Hi, I'm Seyoung.

I want to use your code in my commercial app.
But I can'f find any terms and conditions for use, reproduction, and distribution.
(I detected MIT License in package.json. But I'm not sure I can use freely.)
I wonder if I can use the code for commercial distribution or not.
Please let me know how I can use the code for commercial distribution.

Thanks.

**Comment by AlirezaMH** [comment]
Hi Seyoung

There aren't any problem and you can use it, but can I know about your app?
